use std::path::PathBuf;

#[allow(dead_code)]
pub struct GameContext {
    pub pid: u32,
    pub exe_path: PathBuf,
    pub install_dir: PathBuf,
    pub bridge_dir: PathBuf,
    pub compat_data_path: Option<PathBuf>,
}

pub struct GameBridge {
    /// Slug identifying the game. Names the game's persistent bridge directory.
    pub name: &'static str,
    pub process_names: &'static [&'static str],
    /// Symlink every directory sitting alongside the game exe into the bridge
    /// dir, for games whose tools resolve data relative to the running exe.
    pub link_sibling_dirs: bool,
    pub from_linux_args: &'static [&'static str],
    pub setup: Option<fn(&GameContext) -> anyhow::Result<()>>,
    pub teardown: Option<fn(&GameContext) -> anyhow::Result<()>>,
}

pub static GAMES: &[GameBridge] = &[
    GameBridge {
        name: "assetto-corsa",
        process_names: &["acs.exe"],
        link_sibling_dirs: true,
        from_linux_args: &[
            "--from-linux",
            r"acpmf_physics|Local\acpmf_physics",
            "--from-linux",
            r"acpmf_graphics|Local\acpmf_graphics",
            "--from-linux",
            r"acpmf_static|Local\acpmf_static",
            "--from-linux",
            r"acpmf_simhub_v2|Local\acpmf_simhub_v2",
            "--from-linux",
            r"acpmf_crewchief|Local\acpmf_crewchief",
            "--from-linux",
            r"acpmf_secondMonitor|Local\acpmf_secondMonitor",
        ],
        setup: None,
        teardown: None,
    },
    GameBridge {
        name: "assetto-corsa-competizione",
        process_names: &["AC2-Win64-Shipping.exe"],
        link_sibling_dirs: false,
        from_linux_args: &[
            "--from-linux",
            r"acpmf_physics|Local\acpmf_physics",
            "--from-linux",
            r"acpmf_graphics|Local\acpmf_graphics",
            "--from-linux",
            r"acpmf_static|Local\acpmf_static",
        ],
        setup: None,
        teardown: None,
    },
    GameBridge {
        name: "assetto-corsa-evo",
        process_names: &["AssettoCorsaEVO.exe"],
        link_sibling_dirs: false,
        from_linux_args: &[
            "--from-linux",
            r"acevo_pmf_static|Local\acevo_pmf_static",
            "--from-linux",
            r"acevo_pmf_physics|Local\acevo_pmf_physics",
            "--from-linux",
            r"acevo_pmf_graphics|Local\acevo_pmf_graphics",
        ],
        setup: None,
        teardown: None,
    },
    GameBridge {
        name: "assetto-corsa-rally",
        process_names: &["acr.exe"],
        link_sibling_dirs: false,
        from_linux_args: &[
            "--from-linux",
            r"acpmf_physics|Local\acpmf_physics",
            "--from-linux",
            r"acpmf_graphics|Local\acpmf_graphics",
            "--from-linux",
            r"acpmf_static|Local\acpmf_static",
        ],
        setup: None,
        teardown: None,
    },
    GameBridge {
        name: "rfactor2",
        process_names: &["rFactor2.exe"],
        link_sibling_dirs: false,
        from_linux_args: &[
            "--from-linux",
            "$rFactor2SMMP_Telemetry$",
            "--from-linux",
            "$rFactor2SMMP_Scoring$",
            "--from-linux",
            "$rFactor2SMMP_Rules$",
            "--from-linux",
            "$rFactor2SMMP_MultiRules$",
            "--from-linux",
            "$rFactor2SMMP_ForceFeedback$",
            "--from-linux",
            "$rFactor2SMMP_Graphics$",
            "--from-linux",
            "$rFactor2SMMP_Extended$",
            "--from-linux",
            "$rFactor2SMMP_PitInfo$",
            "--from-linux",
            "$rFactor2SMMP_Weather$",
            "--from-linux",
            "$rFactor2SMMP_HWControl$",
            "--from-linux",
            "$rFactor2SMMP_WeatherControl$",
            "--from-linux",
            "$rFactor2SMMP_RulesControl$",
            "--from-linux",
            "$rFactor2SMMP_PluginControl$",
        ],
        setup: None,
        teardown: None,
    },
    GameBridge {
        name: "le-mans-ultimate",
        process_names: &["Le Mans Ultimate.exe"],
        link_sibling_dirs: true,
        from_linux_args: &[
            "--from-linux",
            "LMU_Data",
            "--from-linux",
            "$rFactor2SMMP_Telemetry$",
            "--from-linux",
            "$rFactor2SMMP_Scoring$",
            "--from-linux",
            "$rFactor2SMMP_Rules$",
            "--from-linux",
            "$rFactor2SMMP_MultiRules$",
            "--from-linux",
            "$rFactor2SMMP_ForceFeedback$",
            "--from-linux",
            "$rFactor2SMMP_Graphics$",
            "--from-linux",
            "$rFactor2SMMP_Extended$",
            "--from-linux",
            "$rFactor2SMMP_PitInfo$",
            "--from-linux",
            "$rFactor2SMMP_Weather$",
            "--from-linux",
            "$rFactor2SMMP_HWControl$",
            "--from-linux",
            "$rFactor2SMMP_WeatherControl$",
            "--from-linux",
            "$rFactor2SMMP_RulesControl$",
            "--from-linux",
            "$rFactor2SMMP_PluginControl$",
        ],
        setup: None,
        teardown: None,
    },
    GameBridge {
        name: "project-cars-2",
        process_names: &["pCARS2AVX.exe"],
        link_sibling_dirs: false,
        from_linux_args: &["--from-linux", "$pcars2$"],
        setup: None,
        teardown: None,
    },
    GameBridge {
        name: "automobilista-2",
        process_names: &["AMS2AVX.exe"],
        link_sibling_dirs: false,
        from_linux_args: &["--from-linux", "$pcars2$"],
        setup: None,
        teardown: None,
    },
    GameBridge {
        name: "euro-truck-simulator-2",
        process_names: &["eurotrucks2.exe"],
        link_sibling_dirs: false,
        from_linux_args: &["--from-linux", r"SHSCSTelemetry|Local\SHSCSTelemetry"],
        setup: None,
        teardown: None,
    },
    GameBridge {
        name: "american-truck-simulator",
        process_names: &["amtrucks.exe"],
        link_sibling_dirs: false,
        from_linux_args: &["--from-linux", r"SHSCSTelemetry|Local\SHSCSTelemetry"],
        setup: None,
        teardown: None,
    },
];
