[toolchain]
channel = "1.95"
components = [ "cargo", "rustfmt", "rust-src", "rust-analyzer", "clippy" ]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "x86_64-pc-windows-gnu"
]
